OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"